OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"